OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"